OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"